OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"